[project]
name = "LogTT"
version = "0.1.0"
description = "结构化日志分析与可视化系统"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "duckdb>=1.4.4",
    "loguru>=0.7.3",
    "polars>=1.37.1",
    "pyarrow>=23.0.0",
    "pyside6-fluent-widgets[full]>=1.11.0",
    "regex>=2026.1.15",
    "scipy>=1.17.0",
]
