Android:
  log_format: '<Date> <Time>  <Pid>  <Tid> <Level> <Component>: <Content>'
  regex:
    - (/[\w-]+)+
    - ([\w-]+\.){2,}[\w-]+
    - \b(\-?\+?\d+)\b|\b0[Xx][a-fA-F\d]+\b|\b[a-fA-F\d]{4,}\b
Apache:
  log_format: \[<Time>\] \[<Level>\] <Content>
  regex:
    - (\d+\.){3}\d+
BGL:
  log_format: <Label> <Timestamp> <Date> <Node> <Time> <NodeRepeat> <Type> <Component> <Level> <Content>
  regex:
    - core\.\d+
    - \d+:[a-fA-F0-9]{8,}
    - '[a-fA-F0-9]{8,}'
HDFS:
  log_format: '<Date> <Time> <Pid> <Level> <Component>: <Content>'
  regex:
    - blk_-?\d+
    - (\d+\.){3}\d+(:\d+)?
HPC:
  log_format: <LogId> <Node> <Component> <State> <Time> <Flag> <Content>
  regex:
    - =\d+
Hadoop:
  log_format: '<Date> <Time> <Level> \[<Process>\] <Component>: <Content>'
  regex:
    - (\d+\.){3}\d+
HealthApp:
  log_format: <Time>\|<Component>\|<Pid>\|<Content>
  regex:
    - \d+##\d+##\d+##\d+##\d+##\d+
    - =\d+
Linux:
  log_format: '<Month> <Date> <Time> <Level> <Component>(\[<PID>\])?: <Content>'
  regex:
    - (\d+\.){3}\d+
    - \d{2}:\d{2}:\d{2}
Mac:
  log_format: '<Month>  <Date> <Time> <User> <Component>\[<PID>\]( \(<Address>\))?: <Content>'
  regex:
    - ([\w-]+\.){2,}[\w-]+
OpenSSH:
  log_format: '<Date> <Day> <Time> <Component> sshd\[<Pid>\]: <Content>'
  regex:
    - (\d+\.){3}\d+
    - ([\w-]+\.){2,}[\w-]+
OpenStack:
  log_format: <Logrecord> <Date> <Time> <Pid> <Level> <Component> \[<ADDR>\] <Content>
  regex:
    - \[instance:\s*(.*?)\]
    - ((\d+\.){3}\d+,?)+
    - /.+?\s', r'\d+
Proxifier:
  log_format: \[<Time>\] <Program> - <Content>
  regex:
    - <\d+\ssec
    - ([\w-]+\.)+[\w-]+(:\d+)?
    - \d{2}:\d{2}(:\d{2})*
    - '[KGTM]B'
Spark:
  log_format: '<Date> <Time> <Level> <Component>: <Content>'
  regex:
    - (\d+\.){3}\d+
    - \b[KGTM]?B\b
    - ([\w-]+\.){2,}[\w-]+
Thunderbird:
  log_format: '<Label> <Timestamp> <Date> <User> <Month> <Day> <Time> <Location> <Component>(\[<PID>\])?: <Content>'
  regex:
    - (\d+\.){3}\d+
Windows:
  log_format: <Date> <Time>, <Level>                  <Component>    <Content>
  regex:
    - 0x.*?\s
Zookeeper:
  log_format: <Date> <Time> - <Level>  \[<Node>:<Component>@<Id>] - <Content>
  regex:
    - (/|)(\d+\.){3}\d+(:\d+)?